//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.Muscle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Muscle_Description {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Muscle_Description() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICS.Muscle.Resources.Muscle.Description", typeof(Muscle_Description).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abductors Description.
        /// </summary>
        internal static string Abductors {
            get {
                return ResourceManager.GetString("Abductors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adductors Description.
        /// </summary>
        internal static string Adductors {
            get {
                return ResourceManager.GetString("Adductors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior Deltoid Description.
        /// </summary>
        internal static string AnteriorDeltoid {
            get {
                return ResourceManager.GetString("AnteriorDeltoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps Brachii Description.
        /// </summary>
        internal static string BicepsBrachii {
            get {
                return ResourceManager.GetString("BicepsBrachii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brachialis Description.
        /// </summary>
        internal static string Brachialis {
            get {
                return ResourceManager.GetString("Brachialis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brachioradialis Description.
        /// </summary>
        internal static string Brachioradialis {
            get {
                return ResourceManager.GetString("Brachioradialis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erector Spinae Description.
        /// </summary>
        internal static string ErectorSpinae {
            get {
                return ResourceManager.GetString("ErectorSpinae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexors Description.
        /// </summary>
        internal static string Flexors {
            get {
                return ResourceManager.GetString("Flexors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrocnemius Description.
        /// </summary>
        internal static string Gastrocnemius {
            get {
                return ResourceManager.GetString("Gastrocnemius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluteus Maximus Description.
        /// </summary>
        internal static string GluteusMaximus {
            get {
                return ResourceManager.GetString("GluteusMaximus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamstrings Description.
        /// </summary>
        internal static string Hamstrings {
            get {
                return ResourceManager.GetString("Hamstrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infraspinatus Description.
        /// </summary>
        internal static string Infraspinatus {
            get {
                return ResourceManager.GetString("Infraspinatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral Deltoid Description.
        /// </summary>
        internal static string LateralDeltoid {
            get {
                return ResourceManager.GetString("LateralDeltoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latissimus Dorsi Description.
        /// </summary>
        internal static string LatissimusDorsi {
            get {
                return ResourceManager.GetString("LatissimusDorsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levator Scapulae Description.
        /// </summary>
        internal static string LevatorScapulae {
            get {
                return ResourceManager.GetString("LevatorScapulae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obliques Description.
        /// </summary>
        internal static string Obliques {
            get {
                return ResourceManager.GetString("Obliques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pectoralis Major Description.
        /// </summary>
        internal static string PectoralisMajor {
            get {
                return ResourceManager.GetString("PectoralisMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pectoralis Minor Description.
        /// </summary>
        internal static string PectoralisMinor {
            get {
                return ResourceManager.GetString("PectoralisMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterior Deltoid Description.
        /// </summary>
        internal static string PosteriorDeltoid {
            get {
                return ResourceManager.GetString("PosteriorDeltoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratus Lumborum Description.
        /// </summary>
        internal static string QuadratusLumborum {
            get {
                return ResourceManager.GetString("QuadratusLumborum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadriceps Description.
        /// </summary>
        internal static string Quadriceps {
            get {
                return ResourceManager.GetString("Quadriceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectus Abdominis Description.
        /// </summary>
        internal static string RectusAbdominis {
            get {
                return ResourceManager.GetString("RectusAbdominis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhomboids Description.
        /// </summary>
        internal static string Rhomboids {
            get {
                return ResourceManager.GetString("Rhomboids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serratus Anterior Description.
        /// </summary>
        internal static string SerratusAnterior {
            get {
                return ResourceManager.GetString("SerratusAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soleus Description.
        /// </summary>
        internal static string Soleus {
            get {
                return ResourceManager.GetString("Soleus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splenius Description.
        /// </summary>
        internal static string Splenius {
            get {
                return ResourceManager.GetString("Splenius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sternocleidomastoid Description.
        /// </summary>
        internal static string Sternocleidomastoid {
            get {
                return ResourceManager.GetString("Sternocleidomastoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscapularis Description.
        /// </summary>
        internal static string Subscapularis {
            get {
                return ResourceManager.GetString("Subscapularis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supraspinatus Description.
        /// </summary>
        internal static string Supraspinatus {
            get {
                return ResourceManager.GetString("Supraspinatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teres Description.
        /// </summary>
        internal static string Teres {
            get {
                return ResourceManager.GetString("Teres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibialis Anterior Description.
        /// </summary>
        internal static string TibialisAnterior {
            get {
                return ResourceManager.GetString("TibialisAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transverse Abdominis Description.
        /// </summary>
        internal static string TransverseAbdominis {
            get {
                return ResourceManager.GetString("TransverseAbdominis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapezius Description.
        /// </summary>
        internal static string Trapezius {
            get {
                return ResourceManager.GetString("Trapezius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triceps Brachii Description.
        /// </summary>
        internal static string TricepsBrachii {
            get {
                return ResourceManager.GetString("TricepsBrachii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist Extendors Description.
        /// </summary>
        internal static string WristExtendors {
            get {
                return ResourceManager.GetString("WristExtendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist Flexors Description.
        /// </summary>
        internal static string WristFlexors {
            get {
                return ResourceManager.GetString("WristFlexors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist Pronator Description.
        /// </summary>
        internal static string WristPronator {
            get {
                return ResourceManager.GetString("WristPronator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist Supinator Description.
        /// </summary>
        internal static string WristSupinator {
            get {
                return ResourceManager.GetString("WristSupinator", resourceCulture);
            }
        }
    }
}
