//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.Muscle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MuscleGroup_Name {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MuscleGroup_Name() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICS.Muscle.Resources.MuscleGroup.Name", typeof(MuscleGroup_Name).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen.
        /// </summary>
        internal static string Abdomen {
            get {
                return ResourceManager.GetString("Abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calve.
        /// </summary>
        internal static string Calve {
            get {
                return ResourceManager.GetString("Calve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forearm.
        /// </summary>
        internal static string Forearm {
            get {
                return ResourceManager.GetString("Forearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip.
        /// </summary>
        internal static string Hip {
            get {
                return ResourceManager.GetString("Hip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Back.
        /// </summary>
        internal static string LowerBack {
            get {
                return ResourceManager.GetString("LowerBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder.
        /// </summary>
        internal static string Shoulder {
            get {
                return ResourceManager.GetString("Shoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thigh.
        /// </summary>
        internal static string Thigh {
            get {
                return ResourceManager.GetString("Thigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Arm.
        /// </summary>
        internal static string UpperArm {
            get {
                return ResourceManager.GetString("UpperArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Back.
        /// </summary>
        internal static string UpperBack {
            get {
                return ResourceManager.GetString("UpperBack", resourceCulture);
            }
        }
    }
}
