// <auto-generated />
using ICS.Equipment;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICS.Equipment.Migrations
{
    [DbContext(typeof(EquipmentDbContext))]
    [Migration("20220720213042_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ICS.Equipment.EquipmentGroup", b =>
                {
                    b.Property<int>("EquipmentGroupId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentGroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("EquipmentGroupId");

                    b.ToTable("EquipmentGroup", "equipment");

                    b.HasData(
                        new
                        {
                            EquipmentGroupId = 1,
                            EquipmentGroupName = "Barbell"
                        },
                        new
                        {
                            EquipmentGroupId = 2,
                            EquipmentGroupName = "Cable"
                        },
                        new
                        {
                            EquipmentGroupId = 3,
                            EquipmentGroupName = "Dumbbell"
                        },
                        new
                        {
                            EquipmentGroupId = 4,
                            EquipmentGroupName = "Lever"
                        },
                        new
                        {
                            EquipmentGroupId = 5,
                            EquipmentGroupName = "Sled"
                        },
                        new
                        {
                            EquipmentGroupId = 6,
                            EquipmentGroupName = "Smith"
                        },
                        new
                        {
                            EquipmentGroupId = 7,
                            EquipmentGroupName = "Band"
                        },
                        new
                        {
                            EquipmentGroupId = 8,
                            EquipmentGroupName = "Suspension"
                        },
                        new
                        {
                            EquipmentGroupId = 9,
                            EquipmentGroupName = "Calisthenics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
