// <auto-generated />
using ICS.Muscle;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICS.Muscle.Migrations
{
    [DbContext(typeof(MuscleDbContext))]
    partial class MuscleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ICS.Muscle.BodyArea", b =>
                {
                    b.Property<int>("BodyAreaId")
                        .HasColumnType("int");

                    b.Property<string>("BodyAreaName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("BodyAreaId");

                    b.ToTable("BodyArea", "muscle");

                    b.HasData(
                        new
                        {
                            BodyAreaId = 100000,
                            BodyAreaName = "Upper Body"
                        },
                        new
                        {
                            BodyAreaId = 200000,
                            BodyAreaName = "Core"
                        },
                        new
                        {
                            BodyAreaId = 300000,
                            BodyAreaName = "Lower Body"
                        });
                });

            modelBuilder.Entity("ICS.Muscle.Joint", b =>
                {
                    b.Property<int>("JointId")
                        .HasColumnType("int");

                    b.Property<string>("JointName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("JointId");

                    b.ToTable("Joint", "muscle");

                    b.HasData(
                        new
                        {
                            JointId = 1,
                            JointName = "Neck"
                        },
                        new
                        {
                            JointId = 2,
                            JointName = "Shoulder"
                        },
                        new
                        {
                            JointId = 3,
                            JointName = "Elbow"
                        },
                        new
                        {
                            JointId = 4,
                            JointName = "Wrist"
                        },
                        new
                        {
                            JointId = 5,
                            JointName = "Upper Back"
                        },
                        new
                        {
                            JointId = 6,
                            JointName = "Lower Back"
                        },
                        new
                        {
                            JointId = 7,
                            JointName = "Hip"
                        },
                        new
                        {
                            JointId = 8,
                            JointName = "Knee"
                        },
                        new
                        {
                            JointId = 9,
                            JointName = "Ankle"
                        });
                });

            modelBuilder.Entity("ICS.Muscle.JointMuscleGroupMap", b =>
                {
                    b.Property<int>("JointId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.HasKey("JointId", "MuscleGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("JointMuscleGroupMap", "muscle");

                    b.HasData(
                        new
                        {
                            JointId = 1,
                            MuscleGroupId = 110000
                        },
                        new
                        {
                            JointId = 2,
                            MuscleGroupId = 110000
                        },
                        new
                        {
                            JointId = 5,
                            MuscleGroupId = 110000
                        },
                        new
                        {
                            JointId = 1,
                            MuscleGroupId = 120000
                        },
                        new
                        {
                            JointId = 2,
                            MuscleGroupId = 120000
                        },
                        new
                        {
                            JointId = 5,
                            MuscleGroupId = 120000
                        },
                        new
                        {
                            JointId = 2,
                            MuscleGroupId = 130000
                        },
                        new
                        {
                            JointId = 2,
                            MuscleGroupId = 140000
                        },
                        new
                        {
                            JointId = 5,
                            MuscleGroupId = 140000
                        },
                        new
                        {
                            JointId = 3,
                            MuscleGroupId = 150000
                        },
                        new
                        {
                            JointId = 2,
                            MuscleGroupId = 150000
                        },
                        new
                        {
                            JointId = 3,
                            MuscleGroupId = 160000
                        },
                        new
                        {
                            JointId = 4,
                            MuscleGroupId = 160000
                        },
                        new
                        {
                            JointId = 5,
                            MuscleGroupId = 210000
                        },
                        new
                        {
                            JointId = 6,
                            MuscleGroupId = 210000
                        },
                        new
                        {
                            JointId = 6,
                            MuscleGroupId = 220000
                        },
                        new
                        {
                            JointId = 7,
                            MuscleGroupId = 310000
                        },
                        new
                        {
                            JointId = 7,
                            MuscleGroupId = 320000
                        },
                        new
                        {
                            JointId = 8,
                            MuscleGroupId = 320000
                        },
                        new
                        {
                            JointId = 8,
                            MuscleGroupId = 330000
                        },
                        new
                        {
                            JointId = 9,
                            MuscleGroupId = 330000
                        });
                });

            modelBuilder.Entity("ICS.Muscle.Muscle", b =>
                {
                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("MuscleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MuscleId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Muscle", "muscle");

                    b.HasData(
                        new
                        {
                            MuscleId = 111000,
                            MuscleGroupId = 110000,
                            MuscleName = "Sternocleidomastoid"
                        },
                        new
                        {
                            MuscleId = 112000,
                            MuscleGroupId = 110000,
                            MuscleName = "Splenius"
                        },
                        new
                        {
                            MuscleId = 121000,
                            MuscleGroupId = 120000,
                            MuscleName = "Anterior Deltoid"
                        },
                        new
                        {
                            MuscleId = 122000,
                            MuscleGroupId = 120000,
                            MuscleName = "Lateral Deltoid"
                        },
                        new
                        {
                            MuscleId = 123000,
                            MuscleGroupId = 120000,
                            MuscleName = "Posterior Deltoid"
                        },
                        new
                        {
                            MuscleId = 124000,
                            MuscleGroupId = 120000,
                            MuscleName = "Supraspinatus"
                        },
                        new
                        {
                            MuscleId = 131000,
                            MuscleGroupId = 130000,
                            MuscleName = "Pectoralis Major"
                        },
                        new
                        {
                            MuscleId = 132000,
                            MuscleGroupId = 130000,
                            MuscleName = "Pectoralis Minor"
                        },
                        new
                        {
                            MuscleId = 133000,
                            MuscleGroupId = 130000,
                            MuscleName = "Serratus Anterior"
                        },
                        new
                        {
                            MuscleId = 141000,
                            MuscleGroupId = 140000,
                            MuscleName = "Latissimus Dorsi"
                        },
                        new
                        {
                            MuscleId = 142000,
                            MuscleGroupId = 140000,
                            MuscleName = "Teres"
                        },
                        new
                        {
                            MuscleId = 143000,
                            MuscleGroupId = 140000,
                            MuscleName = "Trapezius"
                        },
                        new
                        {
                            MuscleId = 145000,
                            MuscleGroupId = 140000,
                            MuscleName = "Levator Scapulae"
                        },
                        new
                        {
                            MuscleId = 146000,
                            MuscleGroupId = 140000,
                            MuscleName = "Rhomboids"
                        },
                        new
                        {
                            MuscleId = 147000,
                            MuscleGroupId = 140000,
                            MuscleName = "Infraspinatus"
                        },
                        new
                        {
                            MuscleId = 148000,
                            MuscleGroupId = 140000,
                            MuscleName = "Subscapularis"
                        },
                        new
                        {
                            MuscleId = 151000,
                            MuscleGroupId = 150000,
                            MuscleName = "Triceps Brachii"
                        },
                        new
                        {
                            MuscleId = 152000,
                            MuscleGroupId = 150000,
                            MuscleName = "Biceps Brachii"
                        },
                        new
                        {
                            MuscleId = 153000,
                            MuscleGroupId = 150000,
                            MuscleName = "Brachialis"
                        },
                        new
                        {
                            MuscleId = 161000,
                            MuscleGroupId = 160000,
                            MuscleName = "Brachioradialis"
                        },
                        new
                        {
                            MuscleId = 162000,
                            MuscleGroupId = 160000,
                            MuscleName = "Wrist Flexors"
                        },
                        new
                        {
                            MuscleId = 163000,
                            MuscleGroupId = 160000,
                            MuscleName = "Wrist Extendors"
                        },
                        new
                        {
                            MuscleId = 164000,
                            MuscleGroupId = 160000,
                            MuscleName = "Wrist Pronator"
                        },
                        new
                        {
                            MuscleId = 165000,
                            MuscleGroupId = 160000,
                            MuscleName = "Wrist Supinator"
                        },
                        new
                        {
                            MuscleId = 211000,
                            MuscleGroupId = 210000,
                            MuscleName = "Quadratus Lumborum"
                        },
                        new
                        {
                            MuscleId = 212000,
                            MuscleGroupId = 210000,
                            MuscleName = "Erector Spinae"
                        },
                        new
                        {
                            MuscleId = 221000,
                            MuscleGroupId = 220000,
                            MuscleName = "Rectus Abdominis"
                        },
                        new
                        {
                            MuscleId = 222000,
                            MuscleGroupId = 220000,
                            MuscleName = "Transverse Abdominis"
                        },
                        new
                        {
                            MuscleId = 223000,
                            MuscleGroupId = 220000,
                            MuscleName = "Obliques"
                        },
                        new
                        {
                            MuscleId = 311000,
                            MuscleGroupId = 310000,
                            MuscleName = "Gluteus Maximus"
                        },
                        new
                        {
                            MuscleId = 312000,
                            MuscleGroupId = 310000,
                            MuscleName = "Abductors"
                        },
                        new
                        {
                            MuscleId = 313000,
                            MuscleGroupId = 310000,
                            MuscleName = "Flexors"
                        },
                        new
                        {
                            MuscleId = 321000,
                            MuscleGroupId = 320000,
                            MuscleName = "Quadriceps"
                        },
                        new
                        {
                            MuscleId = 322000,
                            MuscleGroupId = 320000,
                            MuscleName = "Hamstrings"
                        },
                        new
                        {
                            MuscleId = 323000,
                            MuscleGroupId = 320000,
                            MuscleName = "Adductors"
                        },
                        new
                        {
                            MuscleId = 331000,
                            MuscleGroupId = 330000,
                            MuscleName = "Gastrocnemius"
                        },
                        new
                        {
                            MuscleId = 332000,
                            MuscleGroupId = 330000,
                            MuscleName = "Soleus"
                        },
                        new
                        {
                            MuscleId = 333000,
                            MuscleGroupId = 330000,
                            MuscleName = "Tibialis Anterior"
                        });
                });

            modelBuilder.Entity("ICS.Muscle.MuscleGroup", b =>
                {
                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<int>("BodyAreaId")
                        .HasColumnType("int");

                    b.Property<string>("MuscleGroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MuscleGroupId");

                    b.HasIndex("BodyAreaId");

                    b.ToTable("MuscleGroup", "muscle");

                    b.HasData(
                        new
                        {
                            MuscleGroupId = 110000,
                            BodyAreaId = 100000,
                            MuscleGroupName = "Neck"
                        },
                        new
                        {
                            MuscleGroupId = 120000,
                            BodyAreaId = 100000,
                            MuscleGroupName = "Shoulder"
                        },
                        new
                        {
                            MuscleGroupId = 130000,
                            BodyAreaId = 100000,
                            MuscleGroupName = "Chest"
                        },
                        new
                        {
                            MuscleGroupId = 140000,
                            BodyAreaId = 100000,
                            MuscleGroupName = "Upper Back"
                        },
                        new
                        {
                            MuscleGroupId = 150000,
                            BodyAreaId = 100000,
                            MuscleGroupName = "Upper Arm"
                        },
                        new
                        {
                            MuscleGroupId = 160000,
                            BodyAreaId = 100000,
                            MuscleGroupName = "Forearm"
                        },
                        new
                        {
                            MuscleGroupId = 210000,
                            BodyAreaId = 200000,
                            MuscleGroupName = "Lower Back"
                        },
                        new
                        {
                            MuscleGroupId = 220000,
                            BodyAreaId = 200000,
                            MuscleGroupName = "Abdomen"
                        },
                        new
                        {
                            MuscleGroupId = 310000,
                            BodyAreaId = 300000,
                            MuscleGroupName = "Hip"
                        },
                        new
                        {
                            MuscleGroupId = 320000,
                            BodyAreaId = 300000,
                            MuscleGroupName = "Thigh"
                        },
                        new
                        {
                            MuscleGroupId = 330000,
                            BodyAreaId = 300000,
                            MuscleGroupName = "Calve"
                        });
                });

            modelBuilder.Entity("ICS.Muscle.JointMuscleGroupMap", b =>
                {
                    b.HasOne("ICS.Muscle.Joint", null)
                        .WithMany()
                        .HasForeignKey("JointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICS.Muscle.MuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ICS.Muscle.Muscle", b =>
                {
                    b.HasOne("ICS.Muscle.MuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ICS.Muscle.MuscleGroup", b =>
                {
                    b.HasOne("ICS.Muscle.BodyArea", null)
                        .WithMany()
                        .HasForeignKey("BodyAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
